{% set version = "0.9.8" %}

package:
  name: fcos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fcos/fcos-{{ version }}.tar.gz
  sha256: 1fe061baf2efcd77f78ac7ce8731deace99d6dad5a592387b2b8dab930a95d3a
  patches:
    - patches/0001-fix-renamed-import-from-torch.hub.patch

build:
  number: 2
  skip: true  # [cuda_compiler_version == "None" or cuda_compiler_version == "10.2" or not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 ==2.17
    - ninja
  host:
    - pip
    - python
    - pytorch
    - pytorch *=cuda*
    - numpy
    - ninja
  run:
    - acrv_datasets
    - {{ pin_compatible('numpy') }}
    - py-opencv
    - pycocotools
    - python
    - torchvision
    - yacs
  run_constrained:
    - pytorch *=cuda*

test:
  imports:
    - fcos

about:
  home: https://github.com/best-of-acrv/fcos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: FCOS is a detector for efficiently predicting objects in images
  description: |
    Fully convolutional one-stage object detection (FCOS) is a framework for
    per-pixel prediction of objects in images. FCOS doesn't rely on expensive
    anchor box calculations and their hyper-parameters, which is in contrast to
    state-of-the-art object detectors like RetinaNet, YOLOv3, and Faster R-CNN.
    It includes a Python API, & scripts for command line usage.
  doc_url: https://github.com/best-of-acrv/fcos
  dev_url: https://github.com/best-of-acrv/fcos

extra:
  recipe-maintainers:
    - btalb
    - mikemhenry
    - h-vetinari
