{% set name = "fcos" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29153d4febfe82878cfe44720ae4f828024a10fb26234f004cf8255159220af8
  patches:
    - patches/migrate_from_THC_to_ATen_and_c10.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None" or cuda_compiler_version == "10.2" or not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} 
    - sysroot_linux-64 ==2.17
    - ninja
  host:
    - pip
    - python
    - pytorch
    - pytorch *=cuda*
    - numpy
    - ninja
  run:
    - acrv_datasets
    - {{ pin_compatible('numpy') }}
    - py-opencv
    - pycocotools
    - python
    - torchvision
    - yacs
  run_constrained:
    - pytorch *=cuda*

test:
  imports:
    - fcos

about:
  home: https://github.com/best-of-acrv/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'FCOS is a detector for efficiently predicting objects in images'
  description: |
    Fully convolutional one-stage object detection (FCOS) is a framework for
    per-pixel prediction of objects in images. FCOS doesn't rely on expensive
    anchor box calculations and their hyper-parameters, which is in contrast to
    state-of-the-art object detectors like RetinaNet, YOLOv3, and Faster R-CNN.
    It includes a Python API, & scripts for command line usage.
  doc_url: https://github.com/best-of-acrv/{{ name }}
  dev_url: https://github.com/best-of-acrv/{{ name }}

extra:
  recipe-maintainers:
    - btalb
    - mikemhenry
